language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t tested_image .
  - docker run --detach --name tested_image tested_image /bin/sh

script:
  - docker ps | grep -q tested_image
  - docker inspect tested_image
  - docker stop tested_image

notifications:
  webhooks: 'https://hooks.microbadger.com/images/ernestasposkus/alpackage/YeSB3Aqky9EcteHEpmFgJylhVfQ='
